repos:
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
          - mdformat-black
        # mdformat fights with terraform_docs
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py38-plus]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: [--resolve-all-configs, --settings-file, pyproject.toml]
  - repo: https://github.com/psf/black
    rev: 22.12.0 # Should be updated together with the black version of the jupytext hook.
    hooks:
      - id: black
        name: black (python)
        args: [--config, pyproject.toml]
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-annotations
          - flake8-bugbear
        name: flake8 (python)
        # Breaking up long regex in pre-commit. See https://pre-commit.com/#regular-expressions
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.2.2
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        files: ^airflow_orchestration
